export const products = [
  {
    name: "Java Moss Portion",
    description: "Taxiphyllum barbieri — dense, easy carpet starter for beginners.",
    priceCents: 1299,
    imageUrl: "/catalog/java-moss.svg",
    category: "Moss",
    ecoScore: 5,
    stock: 120,
  },
  {
    name: "Christmas Moss Mat",
    description: "Vesicularia montagnei on stainless grid for instant hardscape accents.",
    priceCents: 1899,
    imageUrl: "/catalog/christmas-moss.svg",
    category: "Moss",
    ecoScore: 5,
    stock: 85,
  },
  {
    name: "Phoenix Moss Clump",
    description: "Fine texture for nano tanks and detailed foregrounds.",
    priceCents: 1499,
    imageUrl: "/catalog/phoenix-moss.svg",
    category: "Moss",
    ecoScore: 4,
    stock: 60,
  },
  {
    name: "Peacock Moss (photo refresh)",
    description: "Taxiphyllum sp. — studio imagery pending; portion size as listed.",
    priceCents: 1699,
    imageUrl: "",
    category: "Moss",
    ecoScore: 5,
    stock: 40,
  },
  {
    name: "Seiryu Stone Selection",
    description: "Grey-blue accent stones with sharp ridges; rinse before use.",
    priceCents: 3499,
    imageUrl: "/catalog/seiryu-stone.svg",
    category: "Rocks",
    ecoScore: 3,
    stock: 45,
  },
  {
    name: "Dragon Stone Pieces",
    description: "Lightweight clay rock with organic holes — ideal iwagumi stacks.",
    priceCents: 4299,
    imageUrl: "/catalog/dragon-stone.svg",
    category: "Rocks",
    ecoScore: 4,
    stock: 32,
  },
  {
    name: "Lava Rock Mesh Bag",
    description: "Porous volcanic rock for biological filtration and moss anchors.",
    priceCents: 999,
    imageUrl: "/catalog/lava-rock.svg",
    category: "Rocks",
    ecoScore: 2,
    stock: 70,
  },
  {
    name: "Ohko Stone Mix",
    description: "Tan layered hardscape stone; plan aquascape layout before filling.",
    priceCents: 3899,
    imageUrl: "/catalog/ohko-stone.svg",
    category: "Rocks",
    ecoScore: 3,
    stock: 28,
  },
  {
    name: "Showpiece Driftwood (display)",
    description: "Large centerpiece wood — display listing; inventory depleted.",
    priceCents: 12999,
    imageUrl: "/catalog/driftwood.svg",
    category: "Rocks",
    ecoScore: 1,
    stock: 0,
  },
  {
    name: "Aquascaping Gel Super Glue",
    description: "Thick cyanoacrylate gel; bonds moss and epiphytes underwater.",
    priceCents: 899,
    imageUrl: "/catalog/super-glue.svg",
    category: "Supplies",
    ecoScore: 3,
    stock: 200,
  },
  {
    name: "All-in-One Aquarium Fertilizer",
    description: "500 ml macro + micro blend for high-light planted tanks.",
    priceCents: 1699,
    imageUrl: "/catalog/fertilizer.svg",
    category: "Supplies",
    ecoScore: 4,
    stock: 90,
  },
  {
    name: "Curved Aquascaping Scissors",
    description: "Stainless spring scissors for trimming carpet plants and moss.",
    priceCents: 2499,
    imageUrl: "/catalog/scissors.svg",
    category: "Supplies",
    ecoScore: 4,
    stock: 55,
  },
  {
    name: "Root Fertilizer Tabs (label TBD)",
    description: "Slow-release substrate tabs — packaging photography not yet uploaded.",
    priceCents: 1199,
    imageUrl: "",
    category: "Supplies",
    ecoScore: 5,
    stock: 150,
  },
  {
    name: "Promotional Moss Sample",
    description: "Limited promotional listing for stock-cap regression checks.",
    priceCents: 499,
    imageUrl: "/catalog/java-moss.svg",
    category: "Moss",
    ecoScore: 5,
    stock: 1,
  },
];
