export const products = [
  {
    name: "Java Moss Portion",
    subtitle: "Beginner-friendly carpet moss",
    sku: "MC-MOSS-JAVA-01",
    description: "Taxiphyllum barbieri — dense, easy carpet starter for beginners.",
    priceCents: 1299,
    imageUrl: "/catalog/java-moss.svg",
    category: "Moss",
    ecoScore: 5,
    stock: 120,
    highlights: [
      "Tolerates low light and no CO₂",
      "Attach to wood, mesh, or stone",
      "Shrimp and fry love the cover",
    ],
    specs: [
      { label: "Species", value: "Taxiphyllum barbieri" },
      { label: "Portion", value: "~3×3 in loose clump" },
      { label: "Growth rate", value: "Moderate" },
      { label: "Tank size", value: "5 gal and up" },
    ],
  },
  {
    name: "Christmas Moss Mat",
    subtitle: "Pre-grown grid for instant texture",
    sku: "MC-MOSS-XMAS-01",
    description: "Vesicularia montagnei on stainless grid for instant hardscape accents.",
    priceCents: 1899,
    imageUrl: "/catalog/christmas-moss.svg",
    category: "Moss",
    ecoScore: 5,
    stock: 85,
    highlights: [
      "Frilly branches for tree and wall scapes",
      "Stainless grid — trim to fit",
      "Stable anchor for shrimps",
    ],
    specs: [
      { label: "Species", value: "Vesicularia montagnei" },
      { label: "Mat size", value: "Approx. 3×5 in on grid" },
      { label: "Light", value: "Low–medium" },
      { label: "CO₂", value: "Optional; faster with CO₂" },
    ],
  },
  {
    name: "Phoenix Moss Clump",
    subtitle: "Fine texture for nano layouts",
    sku: "MC-MOSS-PHX-01",
    description: "Fine texture for nano tanks and detailed foregrounds.",
    priceCents: 1499,
    imageUrl: "/catalog/phoenix-moss.svg",
    category: "Moss",
    ecoScore: 4,
    stock: 60,
    highlights: [
      "Delicate fronds for small-scale scapes",
      "Great for detailed iwagumi accents",
      "Pairs well with small stones",
    ],
    specs: [
      { label: "Texture", value: "Fine, feathery" },
      { label: "Portion", value: "Golf-ball sized clump" },
      { label: "Tank size", value: "Nano recommended" },
      { label: "Trimming", value: "Light, frequent trims" },
    ],
  },
  {
    name: "Peacock Moss (photo refresh)",
    subtitle: "Studio photo pending — same great portion",
    sku: "MC-MOSS-PEA-01",
    description: "Taxiphyllum sp. — studio imagery pending; portion size as listed.",
    priceCents: 1699,
    imageUrl: "",
    category: "Moss",
    ecoScore: 5,
    stock: 40,
    highlights: [
      "Dense, upright growth habit",
      "Strong option for moss walls",
      "Image refresh in progress",
    ],
    specs: [
      { label: "Species", value: "Taxiphyllum sp." },
      { label: "Portion", value: "As listed at checkout" },
      { label: "Water", value: "Soft to moderately hard" },
      { label: "Note", value: "Listing image is placeholder" },
    ],
  },
  {
    name: "Seiryu Stone Selection",
    subtitle: "Classic grey-blue ridge stone",
    sku: "MC-ROCK-SEI-01",
    description: "Grey-blue accent stones with sharp ridges; rinse before use.",
    priceCents: 3499,
    imageUrl: "/catalog/seiryu-stone.svg",
    category: "Rocks",
    ecoScore: 3,
    stock: 45,
    highlights: [
      "Striking vertical lines for mountain layouts",
      "Rinse to clear dust before placing",
      "Mix sizes for natural stacks",
    ],
    specs: [
      { label: "Stone type", value: "Seiryu-style limestone" },
      { label: "Pack", value: "Assorted fist-sized pieces" },
      { label: "Prep", value: "Rinse; test KH/pH in your water" },
      { label: "Hardscape", value: "Iwagumi & layered stacks" },
    ],
  },
  {
    name: "Dragon Stone Pieces",
    subtitle: "Lightweight clay stone with organic holes",
    sku: "MC-ROCK-DRG-01",
    description: "Lightweight clay rock with organic holes — ideal iwagumi stacks.",
    priceCents: 4299,
    imageUrl: "/catalog/dragon-stone.svg",
    category: "Rocks",
    ecoScore: 4,
    stock: 32,
    highlights: [
      "Warm earth tones; lots of planting pockets",
      "Easier to rearrange than dense stone",
      "Natural tunnel shapes for fish paths",
    ],
    specs: [
      { label: "Material", value: "Inert clay / dragon stone" },
      { label: "Weight", value: "Light vs. same-size granite" },
      { label: "Pack", value: "Mixed shapes, hand-selected" },
      { label: "Aquascape style", value: "Iwagumi, nature style" },
    ],
  },
  {
    name: "Lava Rock Mesh Bag",
    subtitle: "Porous rock for filter media & anchors",
    sku: "MC-ROCK-LAV-01",
    description: "Porous volcanic rock for biological filtration and moss anchors.",
    priceCents: 999,
    imageUrl: "/catalog/lava-rock.svg",
    category: "Rocks",
    ecoScore: 2,
    stock: 70,
    highlights: [
      "Huge surface area for biofilm",
      "Tie moss or epiphytes easily",
      "Mesh bag keeps pieces together in sump",
    ],
    specs: [
      { label: "Rock", value: "Natural lava (porous)" },
      { label: "Bag weight", value: "Approx. 2 lb" },
      { label: "Uses", value: "Hardscape, sump media, moss mounts" },
      { label: "Prep", value: "Rinse vigorously before use" },
    ],
  },
  {
    name: "Ohko Stone Mix",
    subtitle: "Layered tan stone for terraced layouts",
    sku: "MC-ROCK-OHK-01",
    description: "Tan layered hardscape stone; plan aquascape layout before filling.",
    priceCents: 3899,
    imageUrl: "/catalog/ohko-stone.svg",
    category: "Rocks",
    ecoScore: 3,
    stock: 28,
    highlights: [
      "Strata-like layers read well in photos",
      "Plan dry layout before adding water",
      "Neutral tones for bright plants",
    ],
    specs: [
      { label: "Stone type", value: "Ohko / dragon-style mix" },
      { label: "Pack", value: "Assorted slabs and chunks" },
      { label: "Planning tip", value: "Sketch layout on tank bottom first" },
      { label: "Color", value: "Tan, cream, warm grey" },
    ],
  },
  {
    name: "Showpiece Driftwood (display)",
    subtitle: "Display listing — currently out of stock",
    sku: "MC-ROCK-DW-01",
    description: "Large centerpiece wood — display listing; inventory depleted.",
    priceCents: 12999,
    imageUrl: "/catalog/driftwood.svg",
    category: "Rocks",
    ecoScore: 1,
    stock: 0,
    highlights: [
      "Dramatic single-piece focal hardscape",
      "Pre-soaked display model shown",
      "Restock notifications coming",
    ],
    specs: [
      { label: "Type", value: "Hardwood centerpiece" },
      { label: "Status", value: "Out of stock (display)" },
      { label: "Tank size", value: "40 gal+ recommended" },
      { label: "Treatment", value: "Boil/soak before real use" },
    ],
  },
  {
    name: "Aquascaping Gel Super Glue",
    subtitle: "Thick CA gel — bonds underwater",
    sku: "MC-SUP-GLU-01",
    description: "Thick cyanoacrylate gel; bonds moss and epiphytes underwater.",
    priceCents: 899,
    imageUrl: "/catalog/super-glue.svg",
    category: "Supplies",
    ecoScore: 3,
    stock: 200,
    highlights: [
      "Gel stays where you put it",
      "Works on wood, stone, and stainless",
      "Keep cap tight — shelf life matters",
    ],
    specs: [
      { label: "Formula", value: "Cyanoacrylate gel" },
      { label: "Volume", value: "20 g tube" },
      { label: "Use", value: "Moss, Anubias, Buce, ferns" },
      { label: "Safety", value: "Avoid skin/eyes; ventilate" },
    ],
  },
  {
    name: "All-in-One Aquarium Fertilizer",
    subtitle: "Macro + micro for high-light tanks",
    sku: "MC-SUP-FER-500",
    description: "500 ml macro + micro blend for high-light planted tanks.",
    priceCents: 1699,
    imageUrl: "/catalog/fertilizer.svg",
    category: "Supplies",
    ecoScore: 4,
    stock: 90,
    highlights: [
      "One bottle for NPK + traces",
      "Dosing cap included",
      "Pair with good flow and maintenance",
    ],
    specs: [
      { label: "Volume", value: "500 ml" },
      { label: "Tank type", value: "Freshwater planted" },
      { label: "Dosing", value: "Follow label; start conservative" },
      { label: "Storage", value: "Room temp, out of sunlight" },
    ],
  },
  {
    name: "Curved Aquascaping Scissors",
    subtitle: "Spring stainless for carpet trims",
    sku: "MC-SUP-SCI-01",
    description: "Stainless spring scissors for trimming carpet plants and moss.",
    priceCents: 2499,
    imageUrl: "/catalog/scissors.svg",
    category: "Supplies",
    ecoScore: 4,
    stock: 55,
    highlights: [
      "Curved blade follows substrate contour",
      "Spring action reduces hand fatigue",
      "Rinse and dry after each session",
    ],
    specs: [
      { label: "Material", value: "Stainless steel" },
      { label: "Length", value: "Approx. 10 in overall" },
      { label: "Best for", value: "Moss, HC, dwarf hairgrass" },
      { label: "Care", value: "Dry after use to prevent spots" },
    ],
  },
  {
    name: "Root Fertilizer Tabs (label TBD)",
    subtitle: "Slow-release root tabs",
    sku: "MC-SUP-TAB-TBD",
    description: "Slow-release substrate tabs — packaging photography not yet uploaded.",
    priceCents: 1199,
    imageUrl: "",
    category: "Supplies",
    ecoScore: 5,
    stock: 150,
    highlights: [
      "Feeds heavy root feeders under gravel",
      "Press deep near root mass",
      "Final packaging art in progress",
    ],
    specs: [
      { label: "Count", value: "10 tabs" },
      { label: "Target plants", value: "Swords, crypts, bulbs" },
      { label: "Frequency", value: "Replace per growth demand" },
      { label: "Note", value: "Label graphics pending" },
    ],
  },
  {
    name: "Promotional Moss Sample",
    subtitle: "Tiny promo portion — great for nano tests",
    sku: "MC-MOSS-PRM-01",
    description: "Limited promotional listing for stock-cap regression checks.",
    priceCents: 499,
    imageUrl: "/catalog/java-moss.svg",
    category: "Moss",
    ecoScore: 5,
    stock: 1,
    highlights: [
      "Low-cost way to trial moss care",
      "Same species as Java Moss listing",
      "Very limited quantity",
    ],
    specs: [
      { label: "Portion", value: "Promo sample size" },
      { label: "Stock note", value: "Often only 1 unit" },
      { label: "Purpose", value: "QA / promo / nano experiments" },
      { label: "Species", value: "Taxiphyllum barbieri" },
    ],
  },
];
